export const IMAGES = {
  degrify_logo: require("../assets/logo.svg").default,
  plus_icon: require("../assets/plus.svg").default,
  home_icon: require("../assets/home.svg").default,
  home_active_icon: require("../assets/home-active.svg").default,
  bar_icon: require("../assets/chart-bar.svg").default,
  bar_icon_active: require("../assets/chart-bar-active.svg").default,
  users_icon: require("../assets/users.svg").default,
  users_icon_active: require("../assets/users-active.svg").default,
  user_icon: require("../assets/user.svg").default,
  user_icon_active: require("../assets/user-active.svg").default,
  logout_icon: require("../assets/logout.svg").default,
  avatar_icon: require("../assets/avatar.png"),
  landing_image: require("../assets/landing-image.svg").default,
  info_icon: require("../assets/info.svg").default,
  verified_tick_icon: require("../assets/verified-tick.svg").default,
  verified_icon: require("../assets/verified.svg").default,
  verified_icon_active: require("../assets/verified-active.svg").default,
  unverified_icon: require("../assets/unverified.svg").default,
  iba_logo: require("../assets/IBA-logo.png"),
};
